### ISSUE TITLE
restart / start / stop

### ISSUE THREAD

**Issue by sasuke37** [kureuil/orion#4]
bonjour,
Est ce que c'est prévu de rajouter des bouton pour redémarrer, arrêter ou démarrer le serveur a partir du panel??

Sinon bon travail pour ce qui est déjà fait :D

Merci d'avance :)

**Comment by unixfox** [comment]
Le projet date, à mon avis pose ta question ici : http://www.bukkit.fr/topic/12228-orion-g%C3%A9rez-votre-serveur-minecraft-depuis-wordpress.

**Comment by kureuil** [comment]
Yo,

Ca fait un bout de temps que je n'ai pas touché au projet mais il me semble que si je n'avais pas implémenté ces fonctionnalités c'est parce que une fois le serveur éteint, il était impossible de le rallumer si [RemoteToolKit](https://bukkit.org/threads/remotetoolkit-restarts-crash-detection-auto-saves-remote-console.674/) n'était pas installé. Or, ce n'était pas le cas pour la majorité des serveurs.

Du coup, pour éviter que les utilisateurs éteignent leur serveur sans pouvoir le rallumer depuis Orion, je n'avais pas rajouté ces boutons.

**Comment by sasuke37** [comment]
ok et merci pour le lien de remoteToolKit que je connaissais pas :D
